version: "3.8"
   
services:  
  expense-db:
    container_name: expense-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=expense_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./src/main/resources:/docker-entrypoint-initdb.d/
  
  expense-service:
    image: ginolocoop/expense-service
    container_name: expense-service
    ports:
      - "8080:8080"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

