spring:
    hibernate:
        hbm2ddl:
            auto: create
    jpa:
        show-sql: true
        hibernate:  
            ddl-auto: create  
            database-platform: org.hibernate.dialect.PostgreSQLDialect  

    datasource:  
        url: "jdbc:postgresql://expense-db:5432/expense-db"  
        username: postgres  
        password: postgres
