spring:
    application:
        name: expense-service
    hibernate:
        hbm2ddl:
            auto: create
    jpa:
        show-sql: true
        hibernate:  
            ddl-auto: create  
            database-platform: org.hibernate.dialect.PostgreSQLDialect  
        
        #hibernate:  
        #    ddl-auto: create  
        #    database-platform: org.hibernate.dialect.H2Dialect
    #datasource:  
        #url: jdbc:h2:mem:expense-db
    datasource:  
        url: "jdbc:postgresql://expense-db:5432/expense-db"  
        username: postgres  
        password: postgres


eureka:
    client:
        registerWithEureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost